# Generated by Django 5.2.5 on 2025-08-14 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True, verbose_name='Name')),
                ('context', models.TextField(verbose_name='Context')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_bot', to='auth.group', verbose_name='Members')),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('body', models.TextField(verbose_name='Prompt')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prompts', to='ai.coursebot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('body', models.TextField(verbose_name='Response')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='responses', to='ai.coursebot')),
                ('prompt', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='response', to='ai.prompt')),
            ],
        ),
    ]
